# Copy to /etc/init/docker-btcd.conf
description "Docker container for btcd p2p node"
start on filesystem and started docker
stop on runlevel [!2345]
respawn
pre-start script
  # Clean-up if left behind
  docker rm -f btcd-node || true

  # Attempt to always update and fail silently if the network isn't ready
  docker pull lnzap/btcd || true
end script
script
  exec docker run --rm -v btcd-data:/btcd --name=btcd-node --rm -p 8333:8333 -p 127.0.0.1:8334:8334 lnzap/btcd
end script
