x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  bitcoind:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VERSION=${BTCD_VERSION}
        - GROUP_ID=10000
        - USER_ID=10000
        - BITCOIN_CORE_SIGNATURE=${GPG_SIGNATURE:-152812300785C96444D3334D17565732E08E5E41}
    image: bitcoind:local
    pull_policy: build
    environment:
        - DISABLEWALLET=1
        - PRINTTOCONSOLE=1
        - TXINDEX=${TXINDEX:-1}
        - RPCUSER=${RPC_USER}
        - RPCPASSWORD=${RPC_PW}
    stop_grace_period: 1m
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8333:8333/tcp
    expose:
      - 8332/tcp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - btc_oneshot
      - -rpcbind=:8332
      - -rpcallowip=0.0.0.0/0
      - -v2transport=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.btc.entrypoints=websecure
      - traefik.http.routers.btc.rule=Host(`${BTC_HOST}.${DOMAIN}`)
      - traefik.http.routers.btc.service=btc
      - traefik.http.routers.btc.tls.certresolver=letsencrypt
      - traefik.http.routers.btclb.entrypoints=websecure
      - traefik.http.routers.btclb.rule=Host(`${BTC_LB}.${DOMAIN}`)
      - traefik.http.routers.btclb.service=btc
      - traefik.http.routers.btclb.tls.certresolver=letsencrypt
      - traefik.http.services.btc.loadbalancer.server.port=8332

volumes:
  bitcoind-data:
