name: publish

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Extract version from Dockerfile
        run: |
          VERSION=$(grep -oP '(?<=ARG VERSION=).*' Dockerfile)
          echo "::set-env name=DOCKER_TAG::$VERSION"

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/armhf,linux/arm
          tags: |
            lcd1232/bitcoind:${{ env.DOCKER_TAG }}
            lcd1232/bitcoind:latest
